// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqrhjbrjktdlejuvfqel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxcmhqYnJqa3RkbGVqdXZmcWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjc1OTcsImV4cCI6MjA2MDY0MzU5N30.8oy1DZthSIeG4Pd0uYAjVc-XKCLo-6WxuZiet6zhlrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);